# Generated by Django 4.1.1 on 2022-09-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('userEmail', models.CharField(max_length=155)),
                ('userPhone', models.CharField(max_length=10)),
                ('userAddress', models.CharField(max_length=255)),
            ],
        ),
    ]
